### ISSUE TITLE
Code does not work on ATEM 1 M/E Production Studio 4K

### ISSUE THREAD

**Issue by JamesFinchDJ** [kris-sum/AtemSwitcher#1]
Hi I'm receiving this error this does not work on ATEM 1 M/E Production Studio 4K

Connecting to 172.16.1.206 ...
Connected

Unhandled Exception: System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'BMDSwitcherAPI.IBMDSwitcherFairlightAudioMixer'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{BC625428-D969-4512-9462-8AF8B65F0B21}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at AtemAudioMonitorSwitcher.AtemSwitcher.fetchAudioInputs() in C:\workspace\atem-controller\repo\AtemAudioMonitorSwitcher\AtemSwitcher.cs:line 82
   at AtemAudioMonitorSwitcher.AtemSwitcher.Connect(String ipAddress) in C:\workspace\atem-controller\repo\AtemAudioMonitorSwitcher\AtemSwitcher.cs:line 32
   at AtemAudioMonitorSwitcher.Program.RunListInputs(DefaultVerbOption opts) in C:\workspace\atem-controller\repo\AtemAudioMonitorSwitcher\Program.cs:line 62
   at AtemAudioMonitorSwitcher.Program.<>c.<Main>b__3_0(DefaultVerbOption opts) in C:\workspace\atem-controller\repo\AtemAudioMonitorSwitcher\Program.cs:line 54
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 notParsedFunc)
   at AtemAudioMonitorSwitcher.Program.Main(String[] args) in C:\workspace\atem-controller\repo\AtemAudioMonitorSwitcher\Program.cs:line 52

C:\Users\James\Desktop\AtemAudioMonitorSwitcher\Release>

**Comment by kris-sum** [comment]
Thanks for the report - the code is currently only designed to work with devices that have a fairlight audio mixer like the Atem Mini series, but i'll look at adding other devices when I next get a chance.

(this is going to take a little while as i need to refactor the audio code to make it more device-agnostic)
