### ISSUE TITLE
Unhandled Exception in command window

### ISSUE THREAD

**Issue by jimmyclix** [kris-sum/AtemSwitcher#3]
HI,

I keep getting an "unhandled exception" error whenever I type in any of the commands.  Any thoughts on why this may be occurring?
FULL ERROR BELOW:

Unhandled Exception: System.Runtime.InteropServices.COMException: Retrieving the COM class factory for component with CLSID {ACB00FD2-ABE1-467F-A2D5-5D77001815D1} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at AtemAudioMonitorSwitcher.AtemSwitcher.Connect(String ipAddress) in C:\workspace\atem-controller\repo\AtemAudioMonitorSwitcher\AtemSwitcher.cs:line 25
   at AtemAudioMonitorSwitcher.Program.RunAutoSwitch(AutoSwitchVerbOption opts) in C:\workspace\atem-controller\repo\AtemAudioMonitorSwitcher\Program.cs:line 95
   at AtemAudioMonitorSwitcher.Program.<>c.<Main>b__3_2(AutoSwitchVerbOption opts) in C:\workspace\atem-controller\repo\AtemAudioMonitorSwitcher\Program.cs:line 56
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 notParsedFunc)
   at AtemAudioMonitorSwitcher.Program.Main(String[] args) in C:\workspace\atem-controller\repo\AtemAudioMonitorSwitcher\Program.cs:line 52

**Comment by jimmyclix** [comment]
Update. I believe this occurred due to a software version mismatch.  It would appear your autoswitching is built on software control version 8.10 while I was attempting to run software control version 9.0 on the same computer as the command line.

Once I switched back to version 8.10 the issues seemed to resolve itself.

If there's something more at play here and I just got lucky, I'd be happy to hear any comments, suggestions, etc for future issues.

**Comment by kris-sum** [comment]
Thanks for the heads up @jimmyclix , I'll sort out a new build for the 9.x compatibility!

**Comment by Mikeynez** [comment]
Looks like it's broken again, I have tried different versions from 8.1 to 9.1 and keep getting the above issue. I even tried a direct USB C connection but no luck, not ideal as I want to ISO record. I would really love to get this going.

**Comment by kris-sum** [comment]
@Mikeynez do you get the same error message?

**Comment by noahseis** [comment]
Same Error message:

Connecting to 10.0.0.240 ...

Unhandled Exception: System.Runtime.InteropServices.COMException: Retrieving the COM class factory for component with CLSID {4DB07DF8-72BE-4C0D-BBE6-03B9DFF59B3C} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at AtemAudioMonitorSwitcher.AtemSwitcher.Connect(String ipAddress) in C:\workspace\AtemSwitcher\AtemAudioMonitorSwitcher\AtemSwitcher.cs:line 25
   at AtemAudioMonitorSwitcher.Program.RunAutoSwitch(AutoSwitchVerbOption opts) in C:\workspace\AtemSwitcher\AtemAudioMonitorSwitcher\Program.cs:line 95
   at AtemAudioMonitorSwitcher.Program.Main(String[] args) in C:\workspace\AtemSwitcher\AtemAudioMonitorSwitcher\Program.cs:line 58

**Comment by kris-sum** [comment]
@noahseis Are you using https://github.com/kris-sum/AtemSwitcher/releases/tag/1.0.2 ? What version of the Atem software do you have installed?

**Comment by noahseis** [comment]
Yeah using the 1.02 - from the research so far, looks like a 32 bit 64 bit mismatch. I've downloaded visual studio (eeek) and will see if I can make a change. 

Changed the release for the project to x64 and fingers crossed so far no "Unhandled Exception:" error. 
I'm going to run this back to the studio and give it a shot. - I'll post an update if this fix worked.

![image](https://github.com/kris-sum/AtemSwitcher/assets/5076831/7901b1bb-95c9-461b-8213-aaa0746b841a)

**Comment by noahseis** [comment]
Follow up - that was the issue the 64 bit library needs to be picked for the build process. Tested and working well!
![image](https://github.com/kris-sum/AtemSwitcher/assets/5076831/fc886804-5849-4ff9-b645-3e2d4eb89d60)

**Comment by kris-sum** [comment]
Agreed, I was certain I'd retargeted the build in the last zip file, I'll do it again and upload another one when I'm back in the office!
