### ISSUE TITLE
AtemAudioMonitorSwitcher.exe not able to run

### ISSUE THREAD

**Issue by Mikeynez** [kris-sum/AtemSwitcher#5]
When I run the command AtemAudioMonitorSwitcher.exe [My ATEM mini IP Address] I get the following error. Any clues would be helpfull.
 

Unhandled Exception: System.Runtime.InteropServices.COMException: Retrieving the COM class factory for component with CLSID {4DB07DF8-72BE-4C0D-BBE6-03B9DFF59B3C} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at AtemAudioMonitorSwitcher.AtemSwitcher.Connect(String ipAddress) in C:\workspace\AtemSwitcher\AtemAudioMonitorSwitcher\AtemSwitcher.cs:line 25
   at AtemAudioMonitorSwitcher.Program.RunListInputs(DefaultVerbOption opts) in C:\workspace\AtemSwitcher\AtemAudioMonitorSwitcher\Program.cs:line 62
   at AtemAudioMonitorSwitcher.Program.<>c.<Main>b__3_0(DefaultVerbOption opts) in C:\workspace\AtemSwitcher\AtemAudioMonitorSwitcher\Program.cs:line 54
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 notParsedFunc)
   at AtemAudioMonitorSwitcher.Program.Main(String[] args) in C:\workspace\AtemSwitcher\AtemAudioMonitorSwitcher\Program.cs:line 52

**Comment by kris-sum** [comment]
See https://github.com/kris-sum/AtemSwitcher/releases/tag/1.0.2
